# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ceabcdc413d3f3580c9800bb7ef7742974a86c8175e38877b86f812db9ddc808a79c48975ba33eb94fbf4a60a06855111463a37156286a724e461ebc8b3bde

test:
  secret_key_base: 94be081b02cab3117cd25740d94c6e7bd2ec4d6dd40fcb66b0e0b9b1239341852a17d0d9880f5019df8ec4ae2577c3e9e46a0f55fb68236091c91d4f2f874649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
